version: '3.3'

services:
    db:
      image: mysql:8.1
      container_name: utenti_db
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - 3307:3306
      volumes:
        - mysql-data:/var/lib/mysql

    gestione.utenti:
      build: .
      container_name: gestione.utenti
      depends_on:
        - db
      ports: 
        - 8080:8080
      environment:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      

volumes:
  mysql-data:
